#!/usr/bin/env python3
import argparse
import functools
import os
import os.path as op
import shutil
import subprocess as sp
import re
from pathlib import Path


def get_files(fname, tgt):
    try:
        cmd = ['grep', '-E', r'^\\' + tgt, fname]
        out = sp.check_output(cmd, encoding='utf-8')

        r = re.compile(r'\\' + tgt + r'\{(.*)\}')
        return {r.match(ln).group(1) for ln in out.splitlines()}
    except sp.CalledProcessError:
        return set()


def create_single_tex_file(base_dir: Path, main_file: str) -> list[str]:

    r = re.compile(r"\s*\\input\{(\S+)\}")
    with open(base_dir / main_file, 'r') as f:
        lines = f.read().splitlines()

    i = 0
    while i < len(lines):
        m = r.match(lines[i])
        if m is not None:
            input_file = m.group(1)
            temp_lines = create_single_tex_file(base_dir, input_file)
            if i == 0:
                lines = temp_lines + lines[1:]
            else:
                lines = lines[:i] + temp_lines + lines[i + 1:]
            i += len(temp_lines)
        else:
            i += 1
    return lines


def write_lines(path: Path, lines: list[str]) -> None:
    with open(path, "w", encoding="UTF-8") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('ref1')
    parser.add_argument('ref2', nargs='?')
    parser.add_argument('main')
    parser.add_argument('-q', '--quiet', action='store_true')
    parser.add_argument('--tmp_dir', default='/tmp')
    parser.add_argument('--skip_copy', action='store_true')
    parser.add_argument('--pdf_viewer')
    parser.add_argument('--diff_file')
    parser.add_argument('--patch_files', nargs="+")
    parser.add_argument('--latexengine', default='xelatex')
    parser.add_argument('--no_run_bibtex', action='store_true')
    args = parser.parse_args()

    tmp_dir = Path(args.tmp_dir) / 'tmp_ld'
    old_dir = Path(tmp_dir) / 'old'
    new_dir = Path(tmp_dir) / 'new'
    diff_dir = Path(tmp_dir) / 'diff'

    repo_root = Path.cwd()
    if not (repo_root / '.git').exists():
        raise RuntimeError((
            'This command should be executed from the root directory of '
            'a git repo'))

    if not args.skip_copy:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        shutil.copytree(repo_root, old_dir)
        shutil.copytree(repo_root, new_dir)
        shutil.copytree(repo_root, diff_dir)

    _call = sp.check_call if not args.quiet else \
        functools.partial(sp.check_call, stderr=sp.DEVNULL, stdout=sp.DEVNULL)

    _call(['git', 'stash'], cwd=old_dir)
    _call(['git', 'checkout', args.ref1], cwd=old_dir)

    if args.ref2:
        _call(['git', 'stash'], cwd=new_dir)
        _call(['git', 'checkout', args.ref2], cwd=new_dir)

    old_lines = create_single_tex_file(old_dir, args.main)
    new_lines = create_single_tex_file(new_dir, args.main)

    diff_dir.mkdir(exist_ok=True)
    old_src = diff_dir / "old.tex"
    new_src = diff_dir / "new.tex"
    diff_src = diff_dir / (Path(args.main).stem + "_diff.tex")

    write_lines(old_src, old_lines)
    write_lines(new_src, new_lines)

    with open(diff_src, 'w', encoding="UTF-8") as f:
        _call(['latexdiff', old_src, new_src], stdout=f)

    # build the tex diff
    # sp.check_call(['sed', r'/%DIF /d', '-i', op.join(diff_dir, subfile)])

    # build the pdf
    _call(['git', 'add', '.'], cwd=diff_dir)
    _call(['git', 'commit', '-m', 'apply diff'], cwd=diff_dir)

    if args.diff_file:
        _call(
            ['git', 'apply', "--reject", "--whitespace=fix", args.diff_file],
            cwd=diff_dir
        )

    if args.patch_files:
        _call(["git", "am", "-3"] + args.patch_files, cwd=diff_dir)

    _call([args.latexengine, diff_src], cwd=diff_dir)

    if not args.no_run_bibtex:
        _call(['bibtex', diff_src.parent / diff_src.stem], cwd=diff_dir)
        _call([args.latexengine, diff_src], cwd=diff_dir)
        _call([args.latexengine, mdiff_srcain_basename_diff], cwd=diff_dir)

    diff_pdf = diff_src.parent / (diff_src.stem + ".pdf")
    if args.pdf_viewer:
        sp.Popen([args.pdf_viewer, diff_pdf])


if __name__ == '__main__':
    main()
